# -*- coding: utf-8 -*-
"""
Byg et parametrisk skab headless: STEP (dele + samling), DXF (CNC), produktionstegninger (PDF, flere
sider), FCStd og JSON med alle maal og kilder.

    FreeCADCmd.exe build.py --config configs/26023_skab_500.json --out "<mappe>"

Miljoevariable kan bruges i stedet for argumenter: NICAD_CONFIG, NICAD_OUT.
"""

import datetime
import json
import os
import sys

HER = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
sys.path.insert(0, HER)

import FreeCAD as App
import Import
import Mesh
import Part

from nicad import cabinet, solids, drawings
from nicad.sheet import write_pdf, write_png


def args():
    cfg = os.environ.get("NICAD_CONFIG"); out = os.environ.get("NICAD_OUT")
    av = sys.argv
    for i, a in enumerate(av):
        if a == "--config" and i + 1 < len(av):
            cfg = av[i + 1]
        if a == "--out" and i + 1 < len(av):
            out = av[i + 1]
    if not cfg:
        raise SystemExit("angiv --config <json> (eller NICAD_CONFIG)")
    return cfg, out or os.path.join(HER, "out")


def main():
    cfg_path, out = args()
    os.makedirs(out, exist_ok=True)
    with open(cfg_path, encoding="utf-8") as f:
        cfg = json.load(f)
    cab = cabinet.Cabinet(cfg)
    c = cab.c
    pre = c["dwg_prefix"]
    asm = f"{pre}.000{c['variant_suffix']}"       # samlingens tegningsnummer, fx 006.001.000_1
    dato = datetime.date.today().strftime("%d/%m/%Y")
    csk_spec = (c["screw_d"], c["screw_csk_d"], c["screw_csk_angle"])
    meta = dict(dept="Nem Inventar ApS", techref=cfg.get("techref", ""), created_by="nicad (FreeCAD headless)",
                created_date=dato, approved_by="", doctype="Production drawing", status=cfg.get("status", "FOR REVIEW"),
                project=c["project"], finish=c["finish"], rev=cfg.get("rev", "A"), date=dato,
                model=f"{asm}.FCStd  ·  build.py --config {os.path.basename(cfg_path)}")

    doc = App.newDocument("Cabinet")
    ark = doc.addObject("Spreadsheet::Sheet", "Parametre")
    ark.set("A1", "Parameter"); ark.set("B1", "Value"); ark.set("C1", "Source")
    for i, (k, v) in enumerate(sorted(c.items()), start=2):
        ark.set(f"A{i}", k); ark.set(f"B{i}", str(v)); ark.set(f"C{i}", cab.src.get(k, "DEFAULT"))

    order = [k for k in ("door", "left", "right", "topbottom", "back") if k in cab.parts]
    shapes, report = {}, []
    for key in order:
        p = cab.parts[key]
        shape, n = solids.build(p, csk_spec)
        shapes[key] = shape
        o = doc.addObject("Part::Feature", p.dwg.replace(".", "_")); o.Shape = shape; o.Label = f"{p.dwg} {p.navn}"
        Import.export([o], os.path.join(out, f"{p.dwg}.step"))
        vol_box = p.A * p.B * p.T
        report.append(dict(dwg=p.dwg, navn=p.navn, size=[p.A, p.B, p.T], qty=p.qty, features=n, removed_mm3=round(vol_box - shape.Volume)))
        print(f"[nicad] {p.dwg:12s} {p.A:g}x{p.B:g}x{p.T:g}  features={n:3d}  valid={shape.isValid()}")

    # samling
    inst = []
    grp = doc.addObject("App::Part", "Assembly")
    for navn, p, M, t in cab.assembly():
        key = next(k for k, pp in cab.parts.items() if pp is p)
        o = doc.addObject("Part::Feature", navn); o.Shape = shapes[key]; o.Placement = solids.placement(M, t); o.Label = f"{navn} ({p.dwg})"
        grp.addObject(o); inst.append((navn, p, o))
    doc.recompute()
    overlap = 0.0
    for i in range(len(inst)):
        for j in range(i + 1, len(inst)):
            v = inst[i][2].Shape.common(inst[j][2].Shape).Volume
            if v > 1e-3:
                overlap += v; print(f"[nicad]   OVERLAP {inst[i][0]} x {inst[j][0]}: {v:.1f} mm3")
    comp = Part.makeCompound([o.Shape for _, _, o in inst])
    bb = comp.BoundBox
    print(f"[nicad] assembly bbox X {bb.XMin:.1f}..{bb.XMax:.1f}  Y {bb.YMin:.1f}..{bb.YMax:.1f}  Z {bb.ZMin:.1f}..{bb.ZMax:.1f}  overlap {overlap:.1f} mm3")
    Import.export([o for _, _, o in inst], os.path.join(out, f"{asm}_assembly.step"))
    rd = os.path.join(out, "_render"); os.makedirs(rd, exist_ok=True)
    for navn, _, o in inst:
        Mesh.export([o], os.path.join(rd, f"{asm}_{navn}.stl"))

    # DXF
    from nicad import dxf as dxfmod
    status_line = f"{meta['status']} - generated by nicad build.py from {os.path.basename(cfg_path)}. Verify before cutting."
    dxf_files = []
    for key in order:
        dxf_files += dxfmod.write_part(cab.parts[key], out, csk_spec, status_line)
    print(f"[nicad] DXF: {len(dxf_files)} files")

    # tegninger
    pages = [drawings.assembly_sheet(cab, [(n, p, o.Shape) for n, p, o in inst], meta, 1, len(order) + 1)]
    for i, key in enumerate(order, start=2):
        pages.append(drawings.part_sheet(cab.parts[key], shapes[key], cab, meta, i, len(order) + 1))
    pdf = os.path.join(out, f"{asm}_production-drawings_rev-{meta['rev']}.pdf")
    write_pdf(pages, pdf)
    for i, pg in enumerate(pages, start=1):
        with open(os.path.join(rd, f"{asm}_sheet_{i}.svg"), "w", encoding="utf-8") as f:
            f.write(pg.svg())
        write_png(pg, os.path.join(rd, f"{asm}_sheet_{i}.png"))
    print(f"[nicad] PDF: {os.path.basename(pdf)}  ({len(pages)} sheets, {os.path.getsize(pdf)} bytes)")

    doc.saveAs(os.path.join(out, f"{asm}.FCStd"))
    with open(os.path.join(out, f"{asm}_parameters.json"), "w", encoding="utf-8") as f:
        json.dump(dict(config=cfg, resolved={k: v for k, v in c.items()}, sources=cab.src, derived=cab.antagelser(),
                       bom=[dict(item=i, qty=q, part=pn, desc=d) for i, q, pn, d in cab.bom()], parts=report,
                       assembly_bbox=[bb.XMin, bb.XMax, bb.YMin, bb.YMax, bb.ZMin, bb.ZMax], overlap_mm3=overlap,
                       generated=dato, files=dict(pdf=os.path.basename(pdf), dxf=dxf_files)), f, ensure_ascii=False, indent=2)
    print(f"[nicad] done -> {out}")


if not os.environ.get("_NICAD_RAN"):
    os.environ["_NICAD_RAN"] = "1"           # FreeCADCmd kan koere filen to gange
    try:
        main()
    except Exception:
        import traceback
        traceback.print_exc()
        raise
