-- Storage bucket for headless quote PDF generation.
-- Bucket is private. Access via signed URLs only (generated by edge function).

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'quote-pdfs',
  'quote-pdfs',
  false,
  10485760, -- 10 MB
  ARRAY['application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY['application/pdf'];

-- Service role bypasses RLS automatically — no explicit policy needed for the edge function.
-- The bucket is brand new and private, so without explicit grant policies authenticated users
-- have NO access by default. The deny policies below are belt-and-suspenders defense-in-depth.
-- AS RESTRICTIVE policies are AND'ed with permissive policies — so if a future migration ever
-- adds a permissive grant for quote-pdfs, these still block authenticated access.

DROP POLICY IF EXISTS "quote_pdfs_deny_authenticated_select" ON storage.objects;
CREATE POLICY "quote_pdfs_deny_authenticated_select"
  ON storage.objects AS RESTRICTIVE
  FOR SELECT
  TO authenticated
  USING (bucket_id <> 'quote-pdfs');

DROP POLICY IF EXISTS "quote_pdfs_deny_authenticated_insert" ON storage.objects;
CREATE POLICY "quote_pdfs_deny_authenticated_insert"
  ON storage.objects AS RESTRICTIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id <> 'quote-pdfs');
